// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.8
// source: api/v1/bid/bid.proto

package bid

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidType int32

const (
	BidType_BIDTYPE_NONE      BidType = 0
	BidType_BIDTYPE_INCREMENT BidType = 1
	BidType_BIDTYPE_RAND      BidType = 2
	BidType_BIDTYPE_SNOWFLAKE BidType = 3
)

// Enum value maps for BidType.
var (
	BidType_name = map[int32]string{
		0: "BIDTYPE_NONE",
		1: "BIDTYPE_INCREMENT",
		2: "BIDTYPE_RAND",
		3: "BIDTYPE_SNOWFLAKE",
	}
	BidType_value = map[string]int32{
		"BIDTYPE_NONE":      0,
		"BIDTYPE_INCREMENT": 1,
		"BIDTYPE_RAND":      2,
		"BIDTYPE_SNOWFLAKE": 3,
	}
)

func (x BidType) Enum() *BidType {
	p := new(BidType)
	*p = x
	return p
}

func (x BidType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_bid_bid_proto_enumTypes[0].Descriptor()
}

func (BidType) Type() protoreflect.EnumType {
	return &file_api_v1_bid_bid_proto_enumTypes[0]
}

func (x BidType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidType.Descriptor instead.
func (BidType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_bid_bid_proto_rawDescGZIP(), []int{0}
}

type StringRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StringRes) Reset() {
	*x = StringRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_bid_bid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRes) ProtoMessage() {}

func (x *StringRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_bid_bid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRes.ProtoReflect.Descriptor instead.
func (*StringRes) Descriptor() ([]byte, []int) {
	return file_api_v1_bid_bid_proto_rawDescGZIP(), []int{0}
}

func (x *StringRes) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

//获取ID请求参数
type IdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ckey string `protobuf:"bytes,1,opt,name=ckey,proto3" json:"ckey,omitempty"`
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_bid_bid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_bid_bid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_api_v1_bid_bid_proto_rawDescGZIP(), []int{1}
}

func (x *IdReq) GetCkey() string {
	if x != nil {
		return x.Ckey
	}
	return ""
}

//ID返回实体
type IdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdRes) Reset() {
	*x = IdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_bid_bid_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRes) ProtoMessage() {}

func (x *IdRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_bid_bid_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRes.ProtoReflect.Descriptor instead.
func (*IdRes) Descriptor() ([]byte, []int) {
	return file_api_v1_bid_bid_proto_rawDescGZIP(), []int{2}
}

func (x *IdRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ckey  string  `protobuf:"bytes,1,opt,name=ckey,proto3" json:"ckey,omitempty"`
	Type  BidType `protobuf:"varint,2,opt,name=type,proto3,enum=bid.v1.BidType" json:"type,omitempty"`
	Step  int64   `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Maxid int64   `protobuf:"varint,4,opt,name=maxid,proto3" json:"maxid,omitempty"`
	Intro string  `protobuf:"bytes,5,opt,name=intro,proto3" json:"intro,omitempty"`
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_bid_bid_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_bid_bid_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_api_v1_bid_bid_proto_rawDescGZIP(), []int{3}
}

func (x *AddReq) GetCkey() string {
	if x != nil {
		return x.Ckey
	}
	return ""
}

func (x *AddReq) GetType() BidType {
	if x != nil {
		return x.Type
	}
	return BidType_BIDTYPE_NONE
}

func (x *AddReq) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *AddReq) GetMaxid() int64 {
	if x != nil {
		return x.Maxid
	}
	return 0
}

func (x *AddReq) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

type AddRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRes) Reset() {
	*x = AddRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_bid_bid_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRes) ProtoMessage() {}

func (x *AddRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_bid_bid_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRes.ProtoReflect.Descriptor instead.
func (*AddRes) Descriptor() ([]byte, []int) {
	return file_api_v1_bid_bid_proto_rawDescGZIP(), []int{4}
}

var File_api_v1_bid_bid_proto protoreflect.FileDescriptor

var file_api_v1_bid_bid_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x69, 0x64, 0x2f, 0x62, 0x69, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x69, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x05, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x04, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa,
	0x42, 0x06, 0x72, 0x04, 0x10, 0x01, 0x18, 0x32, 0x52, 0x04, 0x63, 0x6b, 0x65, 0x79, 0x22, 0x17,
	0x0a, 0x05, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa9, 0x01, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x1d, 0x0a, 0x04, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x01, 0x18, 0x32, 0x52, 0x04, 0x63, 0x6b, 0x65,
	0x79, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x69, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x04, 0x73,
	0x74, 0x65, 0x70, 0x12, 0x1d, 0x0a, 0x05, 0x6d, 0x61, 0x78, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x05, 0x6d, 0x61, 0x78,
	0x69, 0x64, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x01, 0x18, 0x32, 0x52, 0x05, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x22, 0x08, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x2a, 0x5b, 0x0a,
	0x07, 0x42, 0x69, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x49, 0x44, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x42, 0x49,
	0x44, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x43, 0x52, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x49, 0x44, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x41, 0x4e,
	0x44, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x42, 0x49, 0x44, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x4e, 0x4f, 0x57, 0x46, 0x4c, 0x41, 0x4b, 0x45, 0x10, 0x03, 0x32, 0xa5, 0x01, 0x0a, 0x03, 0x42,
	0x69, 0x64, 0x12, 0x4f, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x49, 0x64, 0x12, 0x0d, 0x2e, 0x62, 0x69,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x62, 0x69, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x73, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x22, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x49, 0x64, 0x3a, 0x01, 0x2a, 0x5a,
	0x12, 0x12, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x49, 0x64, 0x2f, 0x7b, 0x63, 0x6b,
	0x65, 0x79, 0x7d, 0x12, 0x4d, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x42, 0x69, 0x7a, 0x12, 0x0e, 0x2e,
	0x62, 0x69, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e,
	0x62, 0x69, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x22, 0x23, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x64, 0x42, 0x69,
	0x7a, 0x3a, 0x01, 0x2a, 0x5a, 0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x64, 0x42,
	0x69, 0x7a, 0x42, 0x36, 0x0a, 0x10, 0x62, 0x62, 0x62, 0x69, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x62, 0x69, 0x64, 0x42, 0x0a, 0x42, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x56, 0x31, 0x50, 0x01, 0x5a, 0x14, 0x62, 0x62, 0x62, 0x69, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x62, 0x69, 0x64, 0x3b, 0x62, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_v1_bid_bid_proto_rawDescOnce sync.Once
	file_api_v1_bid_bid_proto_rawDescData = file_api_v1_bid_bid_proto_rawDesc
)

func file_api_v1_bid_bid_proto_rawDescGZIP() []byte {
	file_api_v1_bid_bid_proto_rawDescOnce.Do(func() {
		file_api_v1_bid_bid_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_bid_bid_proto_rawDescData)
	})
	return file_api_v1_bid_bid_proto_rawDescData
}

var file_api_v1_bid_bid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_bid_bid_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_bid_bid_proto_goTypes = []interface{}{
	(BidType)(0),      // 0: bid.v1.BidType
	(*StringRes)(nil), // 1: bid.v1.StringRes
	(*IdReq)(nil),     // 2: bid.v1.IdReq
	(*IdRes)(nil),     // 3: bid.v1.IdRes
	(*AddReq)(nil),    // 4: bid.v1.AddReq
	(*AddRes)(nil),    // 5: bid.v1.AddRes
}
var file_api_v1_bid_bid_proto_depIdxs = []int32{
	0, // 0: bid.v1.AddReq.type:type_name -> bid.v1.BidType
	2, // 1: bid.v1.Bid.GetId:input_type -> bid.v1.IdReq
	4, // 2: bid.v1.Bid.AddBiz:input_type -> bid.v1.AddReq
	3, // 3: bid.v1.Bid.GetId:output_type -> bid.v1.IdRes
	5, // 4: bid.v1.Bid.AddBiz:output_type -> bid.v1.AddRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_bid_bid_proto_init() }
func file_api_v1_bid_bid_proto_init() {
	if File_api_v1_bid_bid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_bid_bid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_bid_bid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_bid_bid_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_bid_bid_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_bid_bid_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_bid_bid_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_bid_bid_proto_goTypes,
		DependencyIndexes: file_api_v1_bid_bid_proto_depIdxs,
		EnumInfos:         file_api_v1_bid_bid_proto_enumTypes,
		MessageInfos:      file_api_v1_bid_bid_proto_msgTypes,
	}.Build()
	File_api_v1_bid_bid_proto = out.File
	file_api_v1_bid_bid_proto_rawDesc = nil
	file_api_v1_bid_bid_proto_goTypes = nil
	file_api_v1_bid_bid_proto_depIdxs = nil
}
